### ISSUE TITLE
Nilai pada $_SESSION['filemanager']['delete_access'] kosong! Sehingga user yang telah mendapatkan hak akses untuk menghapus file tetap tidak bisa menghapusnya.

### ISSUE THREAD

**Issue by arbisyarifudin** [CiFireCMS/cifirecms#1]
Halo Bang. Saya menemukan **bug** nih. Jadi pada session: `$_SESSION['filemanager']['delete_access'] ` disana saya coba cek ternyata kosong setelah saya `ECHO`.  Makanya ketika saya login pakai role group `admin`, saya tetap gak bisa menghapus file. Padahal hak akses admin sudah saya setting utk bisa mendapatkan hak akses **hapus**.

Lalu setelah saya telusuri, ternyata ada **typo** dibagian `controller/l-admin/Auth.php` pada baris ke 127:
`'delete_access' => $this->role->access('filemanager','wdeleteaccess')`
yang seharusnya begini:
`'delete_access' => $this->role->access('filemanager','delete_access')`.

Demikian admin.

**Comment by adimancifi** [comment]
ok. kalo bisa silakan post di grup supaya pengguna yang laen bisa tau bugs ini. thanks 🤓👍🏻
