### ISSUE TITLE
install via composer

### ISSUE THREAD

**Issue by totoprayogo1916** [CiFireCMS/CiFireCMS#13]
kenapa CI tidak diinstall lewat composer setelah dd24faf2b67aecc806276811e1efdfb65dcd1c25 ?
kalau tidak lakukan `composer update`
maka akan muncul notice
https://github.com/CiFireCMS/cifirecms/blob/e2dba66eb12170ff24f1208e74507aade42ae970/public/index.php#L34-L38
sedangkan cuma install https://github.com/CiFireCMS/cifirecms/blob/e2dba66eb12170ff24f1208e74507aade42ae970/composer.json#L12
yang kebanyakan orang gak pakai `.env` ...

**Comment by adimancifi** [comment]
Agak dilema, karna udah 2 kali di paksain. Mulai dari PHP 5.6 di paksain ke PHP 7 dan mau di paksain lagi ke konsep yang lebih modern tapi base CI3 mentok PHP5.6 dan manyak hal yang membuat saya berfikir versi yang sekarang akan mentok suport seuai base CI3 nya. Makanya ini lagi rombak balikin lagi sesuai aslinya (base CI3) dan skalian bikin baru dengan base CI4 supaya bisa suport dengan composer. Dan ada beberapa plugin yang memang udah gak suport banget versi PHPnya.

**Comment by totoprayogo1916** [comment]
CI3 masih aman digunakan untuk php >5.6
saya biasa menggunakan composer untuk project CI3

saya suka menggunakan installer https://github.com/kenjis/codeigniter-composer-installer
dan semuanya aman

**Comment by adimancifi** [comment]
> CI3 masih aman digunakan untuk php >5.6 saya biasa menggunakan composer untuk project CI3
> 
> saya suka menggunakan installer https://github.com/kenjis/codeigniter-composer-installer dan semuanya aman

Kalau begitu untuk versi sekarang ini tetap akan di suport bagi yang masih pake ci3, tapi tetap akan ada CiFireCMS base ci4. Menurut abang gimana?

**Comment by totoprayogo1916** [comment]
tidak masalah ...
yang penting mudah untuk semua ..

**Comment by totoprayogo1916** [comment]
sample lain: https://github.com/enlivenapp/pubvana
