### ISSUE TITLE
A Database Error Occurred

### ISSUE THREAD

**Issue by cakmoel** [CiFireCMS/cifirecms#5]
Operating System : Ubuntu 18.04 
PHP version : 7.4 
MySQL version: 5.7 
Intalasi berhasil kemudian user login dan kemudian muncul a Database Error Occurred, yang semestingya menuju dashborad, tapi muncul error seperti screenshot berikut: 

![Screenshot from 2021-01-24 08-07-27](https://user-images.githubusercontent.com/414011/105617710-5948c000-5e1b-11eb-9bb7-8787035adce3.png)

**Comment by darmariduan** [comment]
Masalah ini di bagian phpmyadminnya di hapus utk variable Group_By nya di hapus aja di sql_mode

**Comment by cakmoel** [comment]
> Masalah ini di bagian phpmyadminnya di hapus utk variable Group_By nya di hapus aja di sql_mode

Saya tidak menggunakan phpmyadmin. terus gimana ?. @darmariduan

**Comment by adimancifi** [comment]
lebih tepatnya bukan di phpmyadmin tapi di MySQL nya. Edit sql_mode nya, cari di google banyak tutorialnya.

**Comment by nirmalakhanza** [comment]
Tolong dong kalau diperbaiki cara penulisan SQL nya. kenapa harus di edit SQL mode nya, pada versi MySQL 5.7 ada fitur default yang mestinya dipakai tetapi gegara cara penulisan SQL nya di Cifire gak benar jadinya Cifire gak bisa berjalan dengan mestinya.

**Comment by nirmalakhanza** [comment]
SQL Mode pada versi MySQL versi 5.7  tidak salah. tetapi cara penerapan query anda perlu dibetulkan. Sehingga menyebabkan error pada database. Ya gini kalau tidal paham mendalam, jadi ngawur.

**Comment by cakmoel** [comment]
> lebih tepatnya bukan di phpmyadmin tapi di MySQL nya. Edit sql_mode nya, cari di google banyak tutorialnya.

Bung, kenapa di close, ini permasalahan belum tuntas sebab saya tidak ingin mematikan fitur  default pada MySQL versi 5.7.

**Comment by adimancifi** [comment]
ini sudah di update
